import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Caixa Eletrônico</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.main}>
          
          <div className={styles.selectMenu}>
            <button className={styles.selectButton}></button>

            <button className={styles.selectButton}></button>

            <button className={styles.selectButton}></button>
          </div>

          <div className={styles.optionsMenu}>
            <h2>Escolha a transação</h2>

            <div className={styles.optionsLine}>
              <button tabIndex={-1}>Opção 1</button>
              <button tabIndex={-1}>Opção 2</button>
            </div>

            <div className={styles.optionsLine}>
              <button tabIndex={-1}>Opção 3</button>
              <button tabIndex={-1}>Opção 4</button>
            </div>

            <div className={styles.optionsLine}>
              <button tabIndex={-1}>Opção 5</button>
              <button tabIndex={-1}>Opção 6</button>
            </div>
          </div>

          <div className={styles.selectMenu}>
            <button className={styles.selectButton}></button>

            <button className={styles.selectButton}></button>

            <button className={styles.selectButton}></button>
          </div>

        </div>
      </main>

    </>
  )
}

export default Home
